openapi: 3.1.0
info:
  version: 1.0.0
  title: CozyWear API
  description: CozyWear API
servers:
  - url: /
    description: Production Server
paths:
  /health-check:
    get:
      responses:
        "200":
          description: All the services are working properly
        "503":
          description: Some/All the services are not working properly

  /accounts/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userType:
                  type: integer
                  examples: [0]
                  minimum: 0
                  maximum: 2

                email:
                  type: string
                  examples: ["email@example.org"]
                  minimum: 16
                  maximum: 64

                password:
                  type: string
                  examples: ["helloworld"]
                  minimum: 8
                  maximum: 16
      responses:
        "200":
          description: The account details provided is valid and the login request has been authorized. A cookie is set containing the session details.

        "401":
          description: The account details provided is not valid and the login request has been rejected

  /accounts/register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userType:
                  type: integer
                  examples: [0]
                  minimum: 0
                  maximum: 2

                name:
                  type: string
                  examples: [abcd]
                  minimum: 1
                  maximum: 32

                email:
                  type: string
                  examples: ["email@example.org"]
                  minimum: 16
                  maximum: 64

                password:
                  type: string
                  examples: ["helloworld"]
                  minimum: 8
                  maximum: 16

      responses:
        "200":
          description: The new account has been registered

        "400":
          description: The account details used for registration have already been used for an another account

        "500":
          description: An error occured while registering a new user account. Try again.

  /merchant/material/add:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageUrl:
                  type: string

                materialName:
                  type: string
                  examples: ["silk"]

                costPerUnit:
                  type: number
                  examples: [40]
                  description: In Indian Rupees (INR)

                stockQuantity:
                  type: integer
                  examples: [10]

      responses:
        "200":
          description: The new material has been added

        "401":
          description: Unauthorised. More description is found in the response body

        "404":
          description: Not found. More description is found in the response body
        
        "500":
          description: An error occured while adding a material. Try again.

  /merchant/material/remove:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                materialId:
                  type: integer
                  examples: [0]

      responses:
        "200":
          description: The material has been removed

        "401":
          description: Unauthorised. More description is found in the response body

        "404":
          description: Not found. More description is found in the response body

        "500":
          description: An error occurred while removing the material. Try again.
  
  /merchant/material/materials:
    get:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lastSeenId:
                  type: string
                  description: It is the id of the material last recieved from this endpoint. If the request is performed for the first time, leave it empty
                  examples: 
                    - bb3f3ffd-0152-415d-ad53-631e9a0fbea7
                pageSize:
                  type: integer
                  description: Number of items to be returned by the endpoint, the maximum amount per request is 50.
                  examples: 
                    - 20
      responses:
        "200":
          description: The request is processed successfully

        "401":
          description: Unauthorised. More description is found in the response body

        "404":
          description: Not found. More description is found in the response body

        "500":
          description: An error occurred while removing the material. Try again.
